name: Build CPU

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build-cpu.yml"
      - "images/cpu/*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build base
        # GitHub Actions run without a TTY device. This is a workaround to get one,
        # based on https://github.com/actions/runner/issues/241#issuecomment-842566950.
        shell: 'script -q -e -c "bash --noprofile --norc -eo pipefail {0}"'
        run: images/cpu/build.sh
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: images/cpu
          file: images/cpu/dockerfile
          platforms: linux/amd64
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tritonserver
