name: Build CPU

on:
  workflow_dispatch:
  workflow_run:
    workflows: ['Buildbase CPU']
    types: [completed]
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/build-cpu.yml"
      - "images/cpu/dockerfile"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [24.08]
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - 
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: images/cpu
          file: images/cpu/dockerfile
          platforms: linux/amd64
          tags: ${{secrets.DOCKERHUB_USERNAME}}/tritonserver:${{matrix.version}}
          build-args: |
            VERSION=${{matrix.version}}